# Define the version of the Compose file format. This determines which features are available and how the file is interpreted.
version: '3'

# Define the services (containers) that make up your application.
services:
  # Define the 'web' service.
  web:
    build: .  # Build the Docker image for the web service using the Dockerfile in the current directory.
    command: gunicorn things_api_project.wsgi:application --bind 0.0.0.0:8000 --workers 4  # Command to start the Gunicorn server with the specified number of workers.
    volumes:
      - .:/code  # Mount the current directory (.) into the container at /code. This allows for live code reloading.
    expose:
      - "8000"

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - web
